services:

  mongo:
    image: mongo:4.4
    restart: always
    attach: false # Disable logging to stdout
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: not-so-secret
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/0000__baseline.js:/docker-entrypoint-initdb.d/0000_baseline.js

  redis:
    image: redis:7.2
    restart: always
    attach: false # Disable logging to stdout
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  identity:
    build:
      context: ./src/identity
      dockerfile: ./Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 4001:4001
    healthcheck:
      test: ["CMD", "curl", "--fail", "--header", "content-type: application/json", "http://localhost:4001/.well-known/openid-configuration"]
      interval: 5s
      timeout: 5s
      retries: 5

  categories:
    build:
      context: .
      dockerfile: ./src/runner/Dockerfile
      args:
        - SERVICE_NAME=categories
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: mongodb://root:not-so-secret@mongo:27017/reviews-poc-db?ssl=false&authSource=admin
      REDIS_CONNECTION_STRING: redis://redis
      SERVICE_NAME: Categories
    healthcheck:
      test: ["CMD", "curl", "--fail", "--header", "content-type: application/json", "http://localhost/graphql?query=%7B__typename%7D"]
      interval: 5s
      timeout: 5s
      retries: 5

  products:
    build:
      context: .
      dockerfile: ./src/runner/Dockerfile
      args:
        - SERVICE_NAME=products
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: mongodb://root:not-so-secret@mongo:27017/reviews-poc-db?ssl=false&authSource=admin
      REDIS_CONNECTION_STRING: redis://redis
      SERVICE_NAME: Products
    healthcheck:
      test: ["CMD", "curl", "--fail", "--header", "content-type: application/json", "http://localhost/graphql?query=%7B__typename%7D"]
      interval: 5s
      timeout: 5s
      retries: 5

  reviews:
    build:
      context: .
      dockerfile: ./src/runner/Dockerfile
      args:
        - SERVICE_NAME=reviews
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: mongodb://root:not-so-secret@mongo:27017/reviews-poc-db?ssl=false&authSource=admin
      REDIS_CONNECTION_STRING: redis://redis
      SERVICE_NAME: Reviews
    healthcheck:
      test: ["CMD", "curl", "--fail", "--header", "content-type: application/json", "http://localhost/graphql?query=%7B__typename%7D"]
      interval: 5s
      timeout: 5s
      retries: 5

  stock:
    build:
      context: .
      dockerfile: ./src/runner/Dockerfile
      args:
        - SERVICE_NAME=stock
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: mongodb://root:not-so-secret@mongo:27017/reviews-poc-db?ssl=false&authSource=admin
      REDIS_CONNECTION_STRING: redis://redis
      SERVICE_NAME: Stock
    healthcheck:
      test: ["CMD", "curl", "--fail", "--header", "content-type: application/json", "http://localhost/graphql?query=%7B__typename%7D"]
      interval: 5s
      timeout: 5s
      retries: 5

  tags:
    build:
      context: .
      dockerfile: ./src/runner/Dockerfile
      args:
        - SERVICE_NAME=tags
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: mongodb://root:not-so-secret@mongo:27017/reviews-poc-db?ssl=false&authSource=admin
      REDIS_CONNECTION_STRING: redis://redis
      SERVICE_NAME: Tags
    healthcheck:
      test: ["CMD", "curl", "--fail", "--header", "content-type: application/json", "http://localhost/graphql?query=%7B__typename%7D"]
      interval: 5s
      timeout: 5s
      retries: 5

  users:
    build:
      context: .
      dockerfile: ./src/runner/Dockerfile
      args:
        - SERVICE_NAME=users
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: mongodb://root:not-so-secret@mongo:27017/reviews-poc-db?ssl=false&authSource=admin
      REDIS_CONNECTION_STRING: redis://redis
      SERVICE_NAME: Users
    healthcheck:
      test: ["CMD", "curl", "--fail", "--header", "content-type: application/json", "http://localhost/graphql?query=%7B__typename%7D"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./src/gateway
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    depends_on:
      categories:
        condition: service_healthy
      products:
        condition: service_healthy
      reviews:
        condition: service_healthy
      stock:
        condition: service_healthy
      tags:
        condition: service_healthy
      users:
        condition: service_healthy
    environment:
      PORT: 4000
      CATEGORIES_URL: http://categories/graphql
      PRODUCTS_URL: http://products/graphql
      REVIEWS_URL: http://reviews/graphql
      STOCK_URL: http://stock/graphql
      TAGS_URL: http://tags/graphql
      USERS_URL: http://users/graphql

  web:
    build:
      context: ./src/web
      dockerfile: ./Dockerfile
    attach: false # Disable logging to stdout
    ports:
      - 3000:3000
    depends_on:
      gateway:
        condition: service_started
